---
kind: pipeline
name: container
steps:

  image: ubuntu:18.04
  commands:
    - env | sort

- name: publish
  image: plugins/gcr
  settings:
    dockerfile: 5.6/Dockerfile
    repo: "${CI_REPO}"
    tags:
    - '${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}'
    json_key:
      from_secret: gcr-rw

trigger:
  branch:
  - master
  - feature/*
  event:
  - push
  - tag
image_pull_secrets:
- gcr-ro
